[package]
name = "raindrop-notebooklm-integration"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
